# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Node.js v14
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Use Next.js build cache # https://nextjs.org/docs/messages/no-cache
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/.next/cache
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]sx?') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
    - name: Build
      run: npm run build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        path: .next/
