# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Node.js v14
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Use Next.js build cache # https://nextjs.org/docs/messages/no-cache
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/.next/cache
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]sx?') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
    - name: Build
      run: npm run build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: |
          .next/
          !.next/cache/
  deploy:
    name: Deploy to App Engine
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: build
        path: .next/
    - name: Modify app.yaml
      shell: bash
      env:
        CLIENT_SECRET: ${{ secrets.YBB_CLIENT_SECRET }}
      run: |
        sed -i "s/asdihfwetur8921736489712364rhgsdfvhjzxcvnbaskdfas/$CLIENT_SECRET/g" app.yaml
    - name: Deploy
      uses: google-github-actions/deploy-appengine@v0.4.0
      with:
        credentials: ${{ secrets.GCP_SA_KEY }}
